apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-distancia
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-distancia
        image: leandrole8/conversao-distancia:v1.0.0
        ports:
        - containerPort: 5000
